#!/bin/sh
# Register the collector as a launchd user agent, the macOS half of the setup.
# The plist is generated rather than committed because launchd needs absolute
# paths and the repository sits somewhere different on every machine.
#
#   sh collector/macos/install.sh [/path/to/python3]
#
# The agent starts at login and restarts if the collector exits. Configuration
# lives in ~/.config/activity-collector/env, which the wrapper sources, so the
# write token never lands in the world-readable plist.

set -eu

collector=$(cd "$(dirname "$0")/.." && pwd)
python=${1:-$(command -v python3)}
label=com.activity-collector
plist="$HOME/Library/LaunchAgents/$label.plist"
config="$HOME/.config/activity-collector"
wrapper="$config/run.sh"

case "$("$python" -c 'import sys; print(sys.version_info >= (3, 11))')" in
  True) ;;
  *) echo "need python 3.11 or newer, $python is $("$python" -V 2>&1)" >&2; exit 1 ;;
esac

mkdir -p "$HOME/Library/LaunchAgents" "$config" "$HOME/.cache/activity-collector"

if [ ! -f "$config/env" ]; then
  cat > "$config/env" <<'ENV'
# Generic device label, never a personal or employer name.
ACTIVITY_MACHINE_ID=personal-mac
# Leave the next two unset to spool locally without uploading anything.
#ACTIVITY_INGEST_URL=http://homeassistant.local:8788/api/ingest
#ACTIVITY_WRITE_TOKEN=
#ACTIVITY_INTERVAL_SECONDS=30
ENV
  chmod 600 "$config/env"
  echo "wrote $config/env, edit it before the collector uploads anything"
fi

cat > "$wrapper" <<WRAPPER
#!/bin/sh
# Generated by collector/macos/install.sh, edit that instead.
set -eu
. "$config/env"
export \$(sed -n 's/^\\([A-Z_][A-Z_0-9]*\\)=.*/\\1/p' "$config/env")
export PYTHONPATH="$collector/src"
exec "$python" -m activity_collector
WRAPPER
chmod 700 "$wrapper"

cat > "$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$label</string>
  <key>ProgramArguments</key>
  <array><string>/bin/sh</string><string>$wrapper</string></array>
  <key>WorkingDirectory</key><string>$collector</string>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ThrottleInterval</key><integer>30</integer>
  <key>StandardOutPath</key><string>$HOME/Library/Logs/activity-collector.log</string>
  <key>StandardErrorPath</key><string>$HOME/Library/Logs/activity-collector.log</string>
</dict>
</plist>
PLIST

launchctl unload "$plist" 2>/dev/null || true
launchctl load "$plist"

echo "loaded $plist"
echo "start now:  launchctl start $label"
echo "logs:       tail -f $HOME/Library/Logs/activity-collector.log"
echo "uninstall:  launchctl unload $plist && rm $plist"
